# Generated by Django 5.1.6 on 2025-03-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_task_options_rename_deadline_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активен'), ('INACTIVE', 'Неактивен'), ('MAINTENANCE', 'На обслуживании')], default='ACTIVE', max_length=15, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Легковой'), ('TRUCK', 'Грузовой'), ('SPECIAL', 'Спецтехника')], default='CAR', max_length=10, verbose_name='Тип транспорта'),
        ),
    ]
