# Generated by Django 5.1.6 on 2025-05-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_vehicle_cargo_capacity_vehicle_chassis_number_and_more'),
    ]

    operations = [
    ]
