# Generated by Django 5.1.6 on 2025-05-13 12:06

import logistics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_vehicle_cargo_capacity_vehicle_chassis_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=logistics.models.vehicle_photo_upload_path, verbose_name='Основное фото'),
        ),
    ]
