# Generated by Django 5.1.6 on 2025-05-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_vehicle_color_vehicle_description_vehicle_main_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='main_photo',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_consumption',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Расход топлива (л/100км)'),
        ),
    ]
