# Generated by Django 5.1.6 on 2025-05-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_remove_vehicle_main_photo_vehicle_fuel_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
