# Generated by Django 5.1.6 on 2025-05-14 10:23

import logistics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_vehicle_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=logistics.models.vehicle_photo_upload_path, verbose_name='Основное фото'),
        ),
    ]
