# Generated by Django 5.1.6 on 2025-05-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_vehicle_main_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='main_photo',
        ),
    ]
