# Generated by Django 5.1.6 on 2025-07-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_task_assignees_alter_task_assigned_to_taskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Основное фото'),
        ),
    ]
