# Generated by Django 5.1.6 on 2025-08-28 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_alter_expense_options_expense_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='gps_altitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Высота (м)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_device_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID GPS устройства'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_enabled',
            field=models.BooleanField(default=False, verbose_name='GPS мониторинг включен'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_engine_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус двигателя'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_fuel_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Уровень топлива (%)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_heading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Направление (градусы)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_ignition_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус зажигания'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_imei',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI GPS устройства'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление GPS'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер SIM GPS устройства'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_satellites',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество спутников'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_signal_quality',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Качество сигнала'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Скорость (км/ч)'),
        ),
        migrations.CreateModel(
            name='VehicleGPSHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время записи')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Скорость (км/ч)')),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Направление (градусы)')),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Высота (м)')),
                ('satellites', models.IntegerField(blank=True, null=True, verbose_name='Количество спутников')),
                ('signal_quality', models.CharField(blank=True, max_length=20, null=True, verbose_name='Качество сигнала')),
                ('fuel_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Уровень топлива (%)')),
                ('engine_status', models.BooleanField(blank=True, null=True, verbose_name='Статус двигателя')),
                ('ignition_status', models.BooleanField(blank=True, null=True, verbose_name='Статус зажигания')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Сырые данные от GPS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_history', to='logistics.vehicle', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'GPS история',
                'verbose_name_plural': 'GPS история',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='logistics_v_vehicle_124a3f_idx'), models.Index(fields=['timestamp'], name='logistics_v_timesta_05a69e_idx')],
            },
        ),
    ]
