# Generated by Django 5.1.6 on 2025-05-24 13:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0014_remove_vehicle_main_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TASK', 'Задача'), ('WAYBILL', 'Путевой лист'), ('EXPENSE', 'Расход'), ('SYSTEM', 'Системное'), ('DOCUMENT', 'Документ')], max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта отправления')),
                ('start_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота отправления')),
                ('end_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта назначения')),
                ('end_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота назначения')),
                ('start_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес отправления')),
                ('end_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес назначения')),
                ('cargo_description', models.TextField(blank=True, verbose_name='Описание груза')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата поездки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='logistics.vehicle', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.trip', verbose_name='Поездка')),
            ],
            options={
                'verbose_name': 'Геолокация водителя',
                'verbose_name_plural': 'Геолокации водителей',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер КАТа')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('departure_point', models.CharField(max_length=255, verbose_name='Пункт отправления')),
                ('destination_point', models.CharField(max_length=255, verbose_name='Пункт назначения')),
                ('cargo_description', models.TextField(blank=True, verbose_name='Описание груза')),
                ('cargo_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес груза (кг)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_created_waybills', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_waybills', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_waybills', to='logistics.vehicle', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Путевой лист',
                'verbose_name_plural': 'Путевые листы',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
