# Generated by Django 5.1.6 on 2025-05-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, verbose_name='Долгота'),
        ),
    ]
