# Generated by Django 5.1.6 on 2025-02-17 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('logistics', '0002_alter_task_options_rename_deadline_task_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер КАТа')),
                ('date', models.DateField(verbose_name='Дата')),
                ('departure_point', models.CharField(max_length=255, verbose_name='Пункт отправления')),
                ('destination_point', models.CharField(max_length=255, verbose_name='Пункт назначения')),
                ('cargo_description', models.TextField(verbose_name='Описание груза')),
                ('cargo_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес груза (кг)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_core_waybills', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_waybills', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='logistics.vehicle', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Путевой лист',
                'verbose_name_plural': 'Путевые листы',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
