# Generated by Django 5.1.6 on 2025-02-17 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_waybill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
