# Generated by Django 5.1.6 on 2025-05-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_driverlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Долгота'),
        ),
    ]
