# Generated by Django 5.1.6 on 2025-06-20 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_driverlocation_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время прибытия'),
        ),
        migrations.AddField(
            model_name='trip',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время отправления'),
        ),
        migrations.AddField(
            model_name='trip',
            name='cargo_status',
            field=models.CharField(choices=[('DIRECT_WAREHOUSE', 'Прямой склад'), ('CUSTOMS_CLEARANCE', 'Растаможка'), ('OTHER', 'Прочее')], default='DIRECT_WAREHOUSE', max_length=30, verbose_name='Статус груза'),
        ),
        migrations.AddField(
            model_name='trip',
            name='cargo_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес груза (кг)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trips', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='trip',
            name='freight_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма фрахта (тг)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('CASH', 'Наличные'), ('TRANSFER', 'Перечисление'), ('CARD', 'Карта')], max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Планируемое время прибытия'),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Планируемое время отправления'),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Запланирована'), ('IN_PROGRESS', 'В пути'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена')], default='PLANNED', max_length=20, verbose_name='Статус поездки'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trailer_description',
            field=models.TextField(blank=True, verbose_name='Описание прицепа'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trailer_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер прицепа'),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
