# Generated by Django 5.1.6 on 2025-06-20 14:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_extend_trip_model'),
        ('logistics', '0015_task_assignees_alter_task_assigned_to_taskfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-planned_start_date', '-created_at'], 'verbose_name': 'Поездка', 'verbose_name_plural': 'Поездки'},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='actual_end_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='actual_start_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='cargo_status',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='planned_end_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='planned_start_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trailer_description',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trailer_number',
        ),
        migrations.AddField(
            model_name='trip',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата окончания'),
        ),
        migrations.AddField(
            model_name='trip',
            name='actual_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата начала'),
        ),
        migrations.AddField(
            model_name='trip',
            name='cargo_type',
            field=models.CharField(choices=[('CUSTOMS', 'Растаможка'), ('DIRECT', 'Прямой склад'), ('OTHER', 'Прочее')], default='OTHER', max_length=20, verbose_name='Тип груза'),
        ),
        migrations.AddField(
            model_name='trip',
            name='freight_payment_type',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('TRANSFER', 'Перечисление')], default='TRANSFER', max_length=20, verbose_name='Тип оплаты фрахта'),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Планируемая дата окончания'),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Планируемая дата начала'),
        ),
        migrations.AddField(
            model_name='trip',
            name='title',
            field=models.CharField(default='Поездка', max_length=200, verbose_name='Название поездки'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailer_trips', to='logistics.vehicle', verbose_name='Прицеп'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trips', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания и дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Запланирована'), ('ACTIVE', 'В пути'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена')], default='PLANNED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='logistics.vehicle', verbose_name='Фура'),
        ),
    ]
