# Generated by Django 5.1.6 on 2025-06-21 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_trip_options_remove_trip_actual_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DOCUMENTS', 'Документы'), ('EXTERNAL_INSPECTION', 'Внешний осмотр'), ('TIRES', 'Состояние шин'), ('LIGHTING', 'Осветительные приборы'), ('ELECTRICAL', 'Электрика'), ('BRAKES', 'Тормозная система'), ('FLUIDS', 'Жидкости'), ('EQUIPMENT', 'Оснащение фуры'), ('DRIVER', 'Водитель')], max_length=30, verbose_name='Категория')),
                ('title', models.CharField(max_length=200, verbose_name='Название проверки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Шаблон чек-листа',
                'verbose_name_plural': 'Шаблоны чек-листов',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VehicleChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает проверки'), ('IN_PROGRESS', 'В процессе проверки'), ('COMPLETED', 'Проверка завершена'), ('APPROVED', 'Одобрено для рейса'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('driver_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания водителем')),
                ('mechanic_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания механиком')),
                ('deputy_director_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания зам. директора')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('checked_by_deputy_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_director_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Проверил зам. директора')),
                ('checked_by_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Проверил водитель')),
                ('checked_by_mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanic_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Проверил механик')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='core.trip', verbose_name='Поездка')),
            ],
            options={
                'verbose_name': 'Чек-лист проверки фуры',
                'verbose_name_plural': 'Чек-листы проверки фур',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DOCUMENTS', 'Документы'), ('EXTERNAL_INSPECTION', 'Внешний осмотр'), ('TIRES', 'Состояние шин'), ('LIGHTING', 'Осветительные приборы'), ('ELECTRICAL', 'Электрика'), ('BRAKES', 'Тормозная система'), ('FLUIDS', 'Жидкости'), ('EQUIPMENT', 'Оснащение фуры'), ('DRIVER', 'Водитель')], max_length=30, verbose_name='Категория')),
                ('title', models.CharField(max_length=200, verbose_name='Название проверки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает проверки'), ('PASS', 'Прошел'), ('FAIL', 'Не прошел'), ('NOT_APPLICABLE', 'Не применимо')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.vehiclechecklist', verbose_name='Чек-лист')),
            ],
            options={
                'verbose_name': 'Элемент чек-листа',
                'verbose_name_plural': 'Элементы чек-листа',
                'ordering': ['category', 'order', 'title'],
                'unique_together': {('checklist', 'category', 'title')},
            },
        ),
    ]
