# Generated by Django 5.1.6 on 2025-03-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_notification_created_at_alter_notification_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='read',
        ),
    ]
