# Generated by Django 5.1.6 on 2025-06-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_checklisttemplate_vehiclechecklist_checklistitem'),
    ]

    operations = [
    ]
