# Generated by Django 5.1.6 on 2025-06-21 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250621_1510'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['template__category', 'template__order'], 'verbose_name': 'Пункт чек-листа', 'verbose_name_plural': 'Пункты чек-листа'},
        ),
        migrations.AlterModelOptions(
            name='checklisttemplate',
            options={'ordering': ['category', 'order', 'title'], 'verbose_name': 'Шаблон чек-листа', 'verbose_name_plural': 'Шаблоны чек-листа'},
        ),
        migrations.RemoveField(
            model_name='checklisttemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='checklisttemplate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='is_ok',
            field=models.BooleanField(default=True, verbose_name='В порядке'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_photos/%Y/%m/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.checklisttemplate', verbose_name='Шаблон пункта'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время проверки'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='category',
            field=models.CharField(choices=[('DOCUMENTS', 'Документы'), ('EXTERNAL_INSPECTION', 'Внешний осмотр'), ('TIRES', 'Состояние шин'), ('LIGHTING', 'Осветительные приборы'), ('ELECTRICAL', 'Электрика'), ('BRAKES', 'Тормозная система'), ('FLUIDS', 'Жидкости'), ('EQUIPMENT', 'Оснащение фуры'), ('DRIVER', 'Водитель')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Обязательный пункт'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название пункта'),
        ),
        migrations.CreateModel(
            name='TripChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает проверки'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершен'), ('APPROVED', 'Утвержден')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('driver_signature', models.CharField(blank=True, max_length=100, verbose_name='Подпись водителя')),
                ('driver_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время подписи водителя')),
                ('mechanic_signature', models.CharField(blank=True, max_length=100, verbose_name='Подпись механика')),
                ('mechanic_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время подписи механика')),
                ('deputy_director_signature', models.CharField(blank=True, max_length=100, verbose_name='Подпись зам директора')),
                ('deputy_director_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время подписи зам директора')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('deputy_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_director_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Зам директор')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanic_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Механик')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='core.trip', verbose_name='Поездка')),
            ],
            options={
                'verbose_name': 'Чек-лист поездки',
                'verbose_name_plural': 'Чек-листы поездок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='checklistitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.tripchecklist', verbose_name='Чек-лист'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistitem',
            unique_together={('checklist', 'template')},
        ),
        migrations.DeleteModel(
            name='VehicleChecklist',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='title',
        ),
    ]
