# Generated by Django 5.1.6 on 2025-06-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_checklistitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='requires_checklist',
            field=models.BooleanField(default=True, verbose_name='Требует чек-лист'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Запланирована'), ('PENDING_CHECKLIST', 'Ожидает чек-лист'), ('READY', 'Готова к отправке'), ('ACTIVE', 'В пути'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена')], default='PLANNED', max_length=20, verbose_name='Статус'),
        ),
    ]
