# Generated by Django 5.1.6 on 2025-05-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_notification_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('TASK', 'Задача'), ('WAYBILL', 'Путевой лист'), ('EXPENSE', 'Расход'), ('SYSTEM', 'Системное'), ('DOCUMENT', 'Документ')], max_length=20, verbose_name='Тип'),
        ),
    ]
