# Generated by Django 4.2.9 on 2025-07-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_checklistitemphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Низкий'), ('NORMAL', 'Обычный'), ('HIGH', 'Высокий'), ('URGENT', 'Срочный')], default='NORMAL', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Прочитано в'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного объекта'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип связанного объекта'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('TASK', 'Задача'), ('WAYBILL', 'Путевой лист'), ('EXPENSE', 'Расход'), ('SYSTEM', 'Системное'), ('DOCUMENT', 'Документ'), ('TRIP', 'Поездка'), ('VEHICLE', 'Транспорт'), ('URGENT', 'Срочное'), ('INFO', 'Информация')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read'], name='core_notifi_user_id_4a178e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'created_at'], name='core_notifi_type_82fbc5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'created_at'], name='core_notifi_priorit_c0cb06_idx'),
        ),
    ]
