# Generated by Django 5.1.6 on 2025-05-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=models.TextField(blank=True, null=True, verbose_name='Сертификаты и достижения'),
        ),
        migrations.AddField(
            model_name='user',
            name='desired_salary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Желаемая зарплата'),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.TextField(blank=True, null=True, verbose_name='Хобби'),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.TextField(blank=True, null=True, verbose_name='Языки'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='user',
            name='recommendation_file',
            field=models.FileField(blank=True, null=True, upload_to='recommendations/', verbose_name='Файл рекомендации'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Навыки'),
        ),
    ]
