# Generated by Django 5.1.6 on 2025-05-22 08:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_age_user_certifications_user_desired_salary_and_more'),
        ('logistics', '0014_remove_vehicle_main_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта отправления')),
                ('start_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота отправления')),
                ('end_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта назначения')),
                ('end_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота назначения')),
                ('cargo_description', models.TextField(blank=True, verbose_name='Описание груза')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата поездки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.user', verbose_name='Водитель')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='logistics.vehicle', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.user', verbose_name='Водитель')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.trip', verbose_name='Поездка')),
            ],
            options={
                'verbose_name': 'Геолокация водителя',
                'verbose_name_plural': 'Геолокации водителей',
                'ordering': ['-timestamp'],
            },
        ),
    ]
