# Generated by Django 4.2.9 on 2025-07-26 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_alter_expense_options_expense_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_improved_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заезд', 'verbose_name_plural': 'Заезды'},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trailer',
        ),
        migrations.AddField(
            model_name='trip',
            name='border_crossing',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пункт пропуска'),
        ),
        migrations.AddField(
            model_name='trip',
            name='cargo_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Объем груза (м³)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trailer_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер прицепа'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cargo_description',
            field=models.TextField(verbose_name='Описание груза'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cargo_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес груза (кг)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_address',
            field=models.CharField(max_length=500, verbose_name='Адрес конца'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта конца'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_longitude',
            field=models.FloatField(default=0.0, verbose_name='Долгота конца'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='freight_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма фрахта'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='freight_payment_type',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('TRANSFER', 'Перечисление')], default='TRANSFER', max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='planned_start_date',
            field=models.DateTimeField(verbose_name='Планируемая дата начала'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_address',
            field=models.CharField(max_length=500, verbose_name='Адрес начала'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта начала'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_longitude',
            field=models.FloatField(default=0.0, verbose_name='Долгота начала'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название заезда'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.vehicle', verbose_name='Транспортное средство'),
        ),
    ]
