# Generated by Django 5.1.6 on 2025-08-10 11:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_trip_model'),
        ('logistics', '0017_alter_expense_options_expense_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-planned_start_date', '-created_at'], 'verbose_name': 'Поездка', 'verbose_name_plural': 'Поездки'},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='border_crossing',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='cargo_volume',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trailer_number',
        ),
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trips', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='trip',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата поездки'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailer_trips', to='logistics.vehicle', verbose_name='Прицеп'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cargo_description',
            field=models.TextField(blank=True, verbose_name='Описание груза'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cargo_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес груза (кг)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес назначения'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта назначения'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота назначения'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='freight_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма фрахта (тг)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='freight_payment_type',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('TRANSFER', 'Перечисление')], default='TRANSFER', max_length=20, verbose_name='Тип оплаты фрахта'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания и дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='planned_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Планируемая дата начала'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес отправления'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта отправления'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота отправления'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(default='Поездка', max_length=200, verbose_name='Название поездки'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='logistics.vehicle', verbose_name='Фура'),
        ),
    ]
