# Generated by Django 5.1.6 on 2025-08-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_trip_options_remove_trip_border_crossing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта назначения'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота назначения'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта отправления'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота отправления'),
        ),
    ]
