# Generated by Django 5.1.6 on 2025-05-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Директор'), ('ACCOUNTANT', 'Бухгалтер'), ('DRIVER', 'Водитель'), ('SUPPLIER', 'Снабженец'), ('TECH', 'Техотдел'), ('ADMIN', 'Администратор'), ('SUPERADMIN', 'Суперадмин')], default='DRIVER', max_length=20, verbose_name='role'),
        ),
    ]
