# Generated by Django 5.1.6 on 2025-02-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=models.TextField(blank=True, verbose_name='certifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.TextField(blank=True, verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.TextField(blank=True, verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.TextField(blank=True, verbose_name='work experience'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Директор'), ('ACCOUNTANT', 'Бухгалтер'), ('DRIVER', 'Водитель'), ('SUPPLIER', 'Снабженец'), ('TECH', 'Техотдел'), ('SUPERADMIN', 'Суперадмин')], default='DRIVER', max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, verbose_name='skills'),
        ),
    ]
