# Generated by Django 5.1.6 on 2025-05-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Директор'), ('ACCOUNTANT', 'Бухгалтер'), ('DRIVER', 'Водитель'), ('SUPPLIER', 'Снабженец'), ('TECH', 'Техотдел'), ('MANAGER', 'Менеджер'), ('DISPATCHER', 'Диспетчер'), ('LOGIST', 'Логист'), ('CONSULTANT', 'Консультант'), ('IT_MANAGER', 'IT-менеджер'), ('ADMIN', 'Администратор'), ('SUPERADMIN', 'Суперадмин'), ('EMPLOYEE', 'Сотрудник')], default='DRIVER', max_length=20, verbose_name='role'),
        ),
    ]
