# Generated by Django 5.1.6 on 2025-02-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_certifications_user_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='about me'),
        ),
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.TextField(blank=True, verbose_name='achievements'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.TextField(blank=True, verbose_name='courses'),
        ),
        migrations.AddField(
            model_name='user',
            name='desired_salary',
            field=models.CharField(blank=True, max_length=50, verbose_name='desired salary'),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.TextField(blank=True, verbose_name='hobbies'),
        ),
        migrations.AddField(
            model_name='user',
            name='key_skills',
            field=models.TextField(blank=True, verbose_name='key skills'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='linkedin'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_url',
            field=models.URLField(blank=True, verbose_name='portfolio url'),
        ),
        migrations.AddField(
            model_name='user',
            name='publications',
            field=models.TextField(blank=True, verbose_name='publications'),
        ),
        migrations.AddField(
            model_name='user',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='recommendations'),
        ),
        migrations.AddField(
            model_name='user',
            name='skype',
            field=models.CharField(blank=True, max_length=50, verbose_name='skype'),
        ),
    ]
