# Generated by Django 5.1.6 on 2025-09-21 18:56

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Директор'), ('ACCOUNTANT', 'Бухгалтер'), ('DRIVER', 'Водитель'), ('SUPPLIER', 'Снабженец'), ('TECH', 'Техотдел'), ('MANAGER', 'Менеджер'), ('DISPATCHER', 'Диспетчер'), ('LOGIST', 'Логист'), ('CONSULTANT', 'Консультант'), ('IT_MANAGER', 'IT-менеджер'), ('DEPUTY_DIRECTOR', 'Зам. директора'), ('SUPERADMIN', 'Суперадмин'), ('EMPLOYEE', 'Сотрудник')], default='DRIVER', max_length=20, verbose_name='role'),
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DRIVER_LICENSE', 'Водительское удостоверение'), ('MEDICAL_CERTIFICATE', 'Медицинская справка'), ('PASSPORT', 'Паспорт'), ('WORK_PERMIT', 'Разрешение на работу'), ('INSURANCE', 'Страховка'), ('OTHER', 'Прочее')], max_length=30, verbose_name='Тип документа')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер документа')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('issuing_authority', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кем выдан')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('file', models.FileField(blank=True, null=True, upload_to=accounts.models.driver_document_upload_path, verbose_name='Файл документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_driver_documents', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'DRIVER'}, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Документ водителя',
                'verbose_name_plural': 'Документы водителей',
                'ordering': ['-issue_date'],
            },
        ),
    ]
