# Generated by Django 5.1.6 on 2025-03-04 11:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_about_me_user_achievements_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommendation_file',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.user_recommendation_path, verbose_name='recommendation file'),
        ),
    ]
