# Generated by Django 5.1.6 on 2025-03-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_recommendation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Designates whether this user is archived and no longer active.', verbose_name='archived'),
        ),
    ]
