# Generated by Django 5.1.6 on 2025-10-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onesignal_player_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OneSignal Player ID'),
        ),
    ]
